# GraphQL Config - used by the GraphQL extension for schema awareness,
# validation, and autocomplete in operations (client).
# https://the-guild.dev/graphql/config/docs

schema: server/schema.graphql
documents: client/src/**/*.{js,jsx,ts,tsx}
